src/main/java/com/memorizmia/core/model/user/User.java
package com.memorizmia.core.model.user;

import com.memorizmia.core.model.user.info.UserInfo;
import com.memorizmia.utils.Patterns;
import com.memorizmia.utils.WordUtils;
import lombok.Data;
import org.hibernate.validator.constraints.NotEmpty;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.authority.SimpleGrantedAuthority;
import org.springframework.security.core.userdetails.UserDetails;

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Past;
import javax.validation.constraints.Pattern;
import java.io.Serializable;
import java.util.*;

@Data
@Entity
public class User implements Serializable, UserDetails {
    private static final long serialVersionUID = 1L;

	@Id
    @GeneratedValue
    private String id;

    @Pattern(regexp = Patterns.EMAIL)
    private String email;
    private String emailConfirmKey;
    private boolean emailConfirmed;
    private String passwordRecoveryKey;

    private String password;

    @NotNull
    @Past
    private Date registrationDate;

    private boolean avatar;

    @NotNull
    @NotEmpty
    @OneToMany
    private List<UserRole> userRoles;

    private boolean enabled;

    private boolean employeeProfileActivated;

    private UserInfo userInfo = new UserInfo();

    private boolean categoriesExistence = false;

    public User() {}

    public String getProfileUri(){
        return "/user/" + id;
    }
    
    public String getFirstName(){
        return userInfo.getFirstName();
    }

    public String getLastName(){
        return userInfo.getLastName();
    }

    public void setFirstName(String firstName){
        userInfo.setFirstName(firstName);
    }

    public void setLastName(String lastName){
        userInfo.setLastName(lastName);
    }

    public String getFullName() {
        return WordUtils.escapeText(String.format("%s %s", userInfo.getFirstName(), userInfo.getLastName()));
    }

    @Override
    public Collection<? extends GrantedAuthority> getAuthorities() {
        List<GrantedAuthority> authorities = new ArrayList<>(userRoles.size());
        for (UserRole userRole : userRoles) {
            authorities.add(new SimpleGrantedAuthority(userRole.toString()));
        }
        return authorities;
    }

    @Override
    public String getPassword() {
        return password;
    }

    @Override
    public String getUsername() {
        return email;
    }

    @Override
    public boolean isAccountNonExpired() {
        return true;
    }

    @Override
    public boolean isAccountNonLocked() {
        return true;
    }

    @Override
    public boolean isCredentialsNonExpired() {
        return true;
    }

    @Override
    public boolean isEnabled() {
        return enabled;
    }

    @Override
    public boolean equals(Object o){
        if(o == null){
            return false;
        }
        if(this.getClass() != o.getClass()){
            return false;
        }
        User u = (User) o;
        return  Objects.equals(email, u.getEmail()) &&
                Objects.equals(userInfo.getFirstName(), u.getFirstName()) &&
                Objects.equals(userInfo.getLastName(), u.getLastName());
    }

    @Override
    public int hashCode(){
        return Objects.hash(email, userInfo.getFirstName(), userInfo.getLastName());
    }
}

src/main/java/com/memorizmia/core/model/user/register/RegistrationData.java
package com.memorizmia.core.model.user.register;

import com.google.common.base.Objects;
import com.memorizmia.utils.Patterns;
import lombok.Getter;
import lombok.Setter;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.validation.constraints.AssertTrue;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Pattern;
import java.io.Serializable;
import java.util.Date;

@Getter
@Setter
public class RegistrationData implements Serializable {
	private static final long serialVersionUID = 1L;

    @Id
    @GeneratedValue
    private long id;

    @NotNull
    @Pattern(regexp = Patterns.EMAIL)
    private String email;

    @NotNull
    @Pattern(regexp = Patterns.NAME)
    private String firstName;

    @NotNull
    @Pattern(regexp = Patterns.NAME)
    private String lastName;

    @NotNull
    @Pattern(regexp = Patterns.PASSWORD)
    private String password;

    private String rePassword;

    private Date registrationDate = new Date();

    @AssertTrue
    public boolean isPasswordsEquals(){
        if(password == null){
            return true;
        }
        return password.equals(rePassword);
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof RegistrationData)) return false;

        RegistrationData data = (RegistrationData) o;
        return  Objects.equal(email, data.getEmail()) &&
                Objects.equal(firstName, data.getFirstName()) &&
                Objects.equal(lastName, data.getLastName()) &&
                Objects.equal(password, data.getPassword()) &&
                Objects.equal(rePassword, data.getRePassword());
    }

    @Override
    public int hashCode() {
        return Objects.hashCode(email, firstName, lastName, password, rePassword);
    }
}

src/main/java/com/memorizmia/web/controller/HomeController.java
package com.memorizmia.web.controller;

import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.servlet.ModelAndView;

/**
 * Created by shved90
 * Date: 10.01.15
 * Time: 10:26
 */
@Controller
@RequestMapping("/")
public class HomeController extends AbstractController {

    @RequestMapping(method = RequestMethod.GET)
    public ModelAndView initHome() {
        return new ModelAndView("index");
    }
}

src/main/java/com/memorizmia/web/controller/LoginController.java
package com.memorizmia.web.controller;

import com.memorizmia.core.model.user.User;
import com.memorizmia.utils.Patterns;
import com.memorizmia.web.utils.JsonResponse;
import com.memorizmia.web.utils.JsonResponseStatus;
import com.memorizmia.web.utils.ViewList;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.authentication.dao.SaltSource;
import org.springframework.security.authentication.encoding.PasswordEncoder;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.servlet.ModelAndView;

import java.util.regex.Pattern;

@Controller
public class LoginController extends AbstractController {
	
	@Autowired
	private PasswordEncoder passwordEncoder;

	@Autowired
	private SaltSource saltSource;
	
	@RequestMapping(value = "/login", method = RequestMethod.GET)
	public ModelAndView login() {
		if (isAutheficated()) {
			return new ModelAndView("redirect:/");
		}
		return new ModelAndView(ViewList.LOGIN_VIEW);
	}

	@RequestMapping(value = "/logout", method = RequestMethod.GET)
	public ModelAndView logout() {
		return new ModelAndView(ViewList.LOGIN_VIEW);
	}

	@RequestMapping(value = "/login/ajax/password-request", method = RequestMethod.GET)
	public ModelAndView passwordRequest() {
		if (isAutheficated()) {
			return new ModelAndView("redirect:/");
		}
		return new ModelAndView("password-request");
	}


    @RequestMapping(value = "/password-request", method = RequestMethod.POST)
    public @ResponseBody
    JsonResponse passwordRequest(String userEmail){
        User user = userService.findByEmail(userEmail);
        if(user == null || !user.isEnabled()) {
            return new JsonResponse(JsonResponseStatus.ERROR, getMessage("user.not.found"));
        }
//        userService.sendPasswordRecoveryKey(user);
        return new JsonResponse(JsonResponseStatus.SUCCESS, getMessage("password.request.send.success"));
    }

	private boolean isPasswordNotValid(String password) {
		return !Pattern.matches(Patterns.PASSWORD, password);
	}
}

src/main/java/com/memorizmia/web/controller/RegisterController.java
package com.memorizmia.web.controller;

import com.memorizmia.core.model.user.User;
import com.memorizmia.core.model.user.register.RegistrationData;
import com.memorizmia.web.messages.SuccessMessage;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.servlet.ModelAndView;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;

import javax.validation.Valid;

@Controller
public class RegisterController extends AbstractController {

    @ModelAttribute
    public void modelAttributes(Model model) {
        super.modelAttributes(model);
        model.addAttribute("title", getMessage("title.register.page"));
    }

    @RequestMapping(value = "/register", method = RequestMethod.GET)
    public ModelAndView registerPageRequest(){
        if(isAutheficated()){
            return new ModelAndView("redirect:/");
        }
        return getRegisterModelAndView(new RegistrationData());
    }

    @RequestMapping(value = "/register", method = RequestMethod.POST)
    public ModelAndView register(@Valid RegistrationData registrationData, BindingResult bindingResult, final RedirectAttributes redirectAttributes){
        if(bindingResult.hasErrors()){
            return getRegisterModelAndView(registrationData);
        }
        User user = userService.register(registrationData);
        doAutoLogin(registrationData.getEmail(), registrationData.getPassword(), user.getAuthorities());
        redirectAttributes.addFlashAttribute("alert", new SuccessMessage("registration.success"));
        return new ModelAndView("redirect:" + user.getProfileUri());
    }

    private ModelAndView getRegisterModelAndView(RegistrationData data) {
        ModelAndView modelAndView = new ModelAndView("register", "registrationData", data);
        return modelAndView;
    }
}

src/main/webapp/WEB-INF/jsp/404.jsp
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags" %>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="s" uri="http://www.springframework.org/tags" %>
<%@ taglib prefix="yt" uri="/WEB-INF/tlds/tags" %>
<%@ taglib prefix="sec" uri="http://www.springframework.org/security/tags" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<html>
<head>
    <title><spring:message code="page.title.404" /></title>
    <meta name="keywords" content="<spring:message code='page.keywords'/>">
    <meta name="description" content="<spring:message code='page.description'/>">
    <link rel="icon" href="/resources/images/loupe/16.png" type="image/x-icon">
    <c:choose>
        <c:when test="${env eq 'DEV'}">
            <link rel="stylesheet/less" type="text/css" href="/resources/less/styles.less">
            <script type="text/javascript">
                less = {
                    env: "development", // or "production"
                    async: false,       // load imports async
                    fileAsync: false,   // load imports async when in a page under
                    poll: 1000         // when in watch mode, time in ms between polls
                };
                localStorage.clear();
            </script>
            <script src="/resources/js/less-1.3.3.min.js"></script>
        </c:when>
        <c:otherwise>
            <link rel="stylesheet" type="text/css" href="/resources/css/styles.css">
        </c:otherwise>
    </c:choose>
</head>
<body>
<sec:authorize access="isAuthenticated()" var="loggedIn" />
<div class="top-menu navbar">
    <div class="container">
        <ul class="nav">
            <li class="mysettings">
                <spring:message code="page.main" var="main"/>
                <yt:urlHandler url="/" text="${main}"/>
            </li>
            <li class="mysettings">
                <spring:message code="search.tasks" var="search_tasks"/>
                <yt:urlHandler url="/search" text="${search_tasks}"/>
            </li>
            <li class="mysettings">
                <spring:message code="employee.search" var="employee_search"/>
                <yt:urlHandler url="/employee-search" text="${employee_search}"/>
            </li>
        </ul>
        <ul class="nav pull-right">
            <c:choose>
                <c:when test="${loggedIn}">
                    <li>
                        <div class="username-block">
                            <div class="username"><a href="/user/${user.id}" >${user.fullName}</a></div>
                            <div class="dropdown-menu">
                                <div class="arrow"></div>
                                <ul class="menu">
                                    <li>
                                        <a class="profile-link" href="/user/${user.id}"><spring:message code="profile" /></a>
                                    </li>
                                    <li>
                                        <a class="tasks-link" href="/user/tasks"><spring:message code="mytasks" /></a>
                                    </li>
                                    <li>
                                        <a class="settings-link" href="/user/settings"><spring:message code="mysettings"/></a>
                                    </li>
                                    <li>
                                        <a class="logout-link" href="/j_spring_security_logout"><spring:message code="logout"/></a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </li>
                </c:when>
                <c:otherwise>
                    <li>
                        <spring:message code="register" var="register"/>
                        <yt:urlHandler url="/register" text="${register}"/>
                    </li>
                    <li>
                        <spring:message code="enter" var="enter"/>
                        <yt:urlHandler url="/login" text="${enter}"/>
                    </li>
                </c:otherwise>
            </c:choose>
        </ul>
        <div class="clear"></div>
    </div>
</div>
<div class="container header">
    <div class="half">
        <a href="/"><img src="/resources/images/logo.png" class="logo"></a>
    </div>
    <div class="half add-task-wrapper">
        <a href="/task/create/" class="btn-warning btn-large">
            <img src="/resources/images/new-task-icon.png"><spring:message code="add.task"/>
        </a>
    </div>
    <div class="clear"></div>
</div>
<div class="container not-found-container">
    <h1><spring:message code="page.404" /></h1>
    <p><spring:message code="page.not.found" /></p>
    <p><spring:message code="can" />
        <c:if test="${not empty referer}">
            <spring:message code="go.back" /> <a href="${referer}"><spring:message code="back" /></a> <spring:message code="or" />
        </c:if>
        <spring:message code="go.to" /> <a href="/"><spring:message code="main.page" /></a></p>
    <div class="not-found"></div>
</div>

<div class="container footer">
    <div class="bottom-menu grey-line">
        <div class="column">
            <ul>
                <c:choose>
                    <c:when test="${loggedIn}">
                        <li><a class="bold" href="/user/${user.id}">${user.fullName}</a></li>
                        <li><a href="/task/create/"><spring:message code="add.task"/></a></li>
                        <li><a href="/user/tasks"><spring:message code="mytasks" /></a></li>
                        <li><a href="/user/settings"><spring:message code="mysettings"/></a></li>
                    </c:when>
                    <c:otherwise>
                        <li><spring:message code="login" /></li>
                        <li><a href="/login"><spring:message code="enter" /></a></li>
                        <li><a href="/register"><spring:message code="register" /></a></li>
                    </c:otherwise>
                </c:choose>
            </ul>
        </div>
        <div class="column">
            <ul>
                <li><spring:message code="search" /></li>
                <li><a href="/search"><spring:message code="search.tasks" /></a></li>
                <li><a href="/employee-search"><spring:message code="employee.search" /></a></li>
            </ul>
        </div>
        <div class="column">
            <ul>
                <li><spring:message code="support" /></li>
                <li><a href="/support/create"><spring:message code="write.us" /></a></li>
            </ul>
        </div>
        <div class="column social-groups">
            <ul>
                <li><spring:message code="we.are.in.social.networks" />:</li>
                <li>
                    <a target="_blank" title="Вконтакте" class="b-share__handle" href="http://vk.com/youtasked"><span class="b-share-icon b-share-icon_vkontakte"></span></a>
                    <a target="_blank" title="Facebook" class="b-share__handle" href="https://www.facebook.com/youtasked"><span class="b-share-icon b-share-icon_facebook"></span></a>
                    <%-- <a target="_blank" title="Twitter" class="b-share__handle" href="#"><span class="b-share-icon b-share-icon_twitter"></span></a>
                     <a target="_blank" title="Одноклассники" class="b-share__handle" href="#"><span class="b-share-icon b-share-icon_odnoklassniki"></span></a>
                     <a target="_blank" title="МойМир" class="b-share__handle" href="#"><span class="b-share-icon b-share-icon_moimir"></span></a>
                     --%><a target="_blank" title="Google+" class="b-share__handle" href="https://plus.google.com/b/105589562294750233643/105589562294750233643"><span class="b-share-icon b-share-icon_gplus"></span></a>
                </li>
            </ul>
        </div>
        <div class="clear"></div>
    </div>
    <div class="copyright grey-line">
        &copy; YouTasked, 2013
    </div>
</div>
</body>
</html>

src/main/webapp/WEB-INF/jsp/500.jsp
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags" %>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="s" uri="http://www.springframework.org/tags" %>
<%@ taglib prefix="yt" uri="/WEB-INF/tlds/tags" %>
<%@ taglib prefix="sec" uri="http://www.springframework.org/security/tags" %>
<html>
<head>
    <title><spring:message code="page.title.500" /></title>
    <meta name="keywords" content="<spring:message code='page.keywords'/>">
    <meta name="description" content="<spring:message code='page.description'/>">
    <link rel="icon" href="/resources/images/loupe/16.png" type="image/x-icon">
    <c:choose>
        <c:when test="${env eq 'DEV'}">
            <link rel="stylesheet/less" type="text/css" href="/resources/less/styles.less">
            <script type="text/javascript">
                less = {
                    env: "development", // or "production"
                    async: false,       // load imports async
                    fileAsync: false,   // load imports async when in a page under
                    poll: 1000         // when in watch mode, time in ms between polls
                };
                localStorage.clear();
            </script>
            <script src="/resources/js/less-1.3.3.min.js"></script>
        </c:when>
        <c:otherwise>
            <link rel="stylesheet" type="text/css" href="/resources/css/styles.css">
        </c:otherwise>
    </c:choose>
</head>
<body>
<sec:authorize access="isAuthenticated()" var="loggedIn" />
<div class="top-menu navbar">
    <div class="container">
        <ul class="nav">
            <li class="mysettings">
                <spring:message code="page.main" var="main"/>
                <yt:urlHandler url="/" text="${main}"/>
            </li>
            <li class="mysettings">
                <spring:message code="search.tasks" var="search_tasks"/>
                <yt:urlHandler url="/search" text="${search_tasks}"/>
            </li>
            <li class="mysettings">
                <spring:message code="employee.search" var="employee_search"/>
                <yt:urlHandler url="/employee-search" text="${employee_search}"/>
            </li>
        </ul>
        <ul class="nav pull-right">
            <c:choose>
                <c:when test="${loggedIn}">
                    <li>
                        <div class="username-block">
                            <div class="username"><a href="/user/${user.id}" >${user.fullName}</a></div>
                            <div class="dropdown-menu">
                                <div class="arrow"></div>
                                <ul class="menu">
                                    <li>
                                        <a class="profile-link" href="/user/${user.id}"><spring:message code="profile" /></a>
                                    </li>
                                    <li>
                                        <a class="tasks-link" href="/user/tasks"><spring:message code="mytasks" /></a>
                                    </li>
                                    <li>
                                        <a class="settings-link" href="/user/settings"><spring:message code="mysettings"/></a>
                                    </li>
                                    <li>
                                        <a class="logout-link" href="/j_spring_security_logout"><spring:message code="logout"/></a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </li>
                </c:when>
                <c:otherwise>
                    <li>
                        <spring:message code="register" var="register"/>
                        <yt:urlHandler url="/register" text="${register}"/>
                    </li>
                    <li>
                        <spring:message code="enter" var="enter"/>
                        <yt:urlHandler url="/login" text="${enter}"/>
                    </li>
                </c:otherwise>
            </c:choose>
        </ul>
        <div class="clear"></div>
    </div>
</div>
<div class="container header">
    <div class="half">
        <a href="/"><img src="/resources/images/logo.png" class="logo"></a>
    </div>
    <div class="half add-task-wrapper">
        <a href="/task/create/" class="btn-warning btn-large">
            <img src="/resources/images/new-task-icon.png"><spring:message code="add.task"/>
        </a>
    </div>
    <div class="clear"></div>
</div>
<div class="container internal-server-error-container">
    <h1><spring:message code="page.500" /></h1>
    <div class="image-text"></div>
</div>

<div class="container footer">
    <div class="bottom-menu grey-line">
        <div class="column">
            <ul>
                <c:choose>
                    <c:when test="${loggedIn}">
                        <li><a class="bold" href="/user/${user.id}">${user.fullName}</a></li>
                        <li><a href="/task/create/"><spring:message code="add.task"/></a></li>
                        <li><a href="/user/tasks"><spring:message code="mytasks" /></a></li>
                        <li><a href="/user/settings"><spring:message code="mysettings"/></a></li>
                    </c:when>
                    <c:otherwise>
                        <li><spring:message code="login" /></li>
                        <li><a href="/login"><spring:message code="enter" /></a></li>
                        <li><a href="/register"><spring:message code="register" /></a></li>
                    </c:otherwise>
                </c:choose>
            </ul>
        </div>
        <div class="column">
            <ul>
                <li><spring:message code="search" /></li>
                <li><a href="/search"><spring:message code="search.tasks" /></a></li>
                <li><a href="/employee-search"><spring:message code="employee.search" /></a></li>
            </ul>
        </div>
        <div class="column">
            <ul>
                <li><spring:message code="support" /></li>
                <li><a href="/support/create"><spring:message code="write.us" /></a></li>
            </ul>
        </div>
        <div class="column social-groups">
            <ul>
                <li><spring:message code="we.are.in.social.networks" />:</li>
                <li>
                    <a target="_blank" title="Вконтакте" class="b-share__handle" href="http://vk.com/youtasked"><span class="b-share-icon b-share-icon_vkontakte"></span></a>
                    <a target="_blank" title="Facebook" class="b-share__handle" href="https://www.facebook.com/youtasked"><span class="b-share-icon b-share-icon_facebook"></span></a>
                    <%-- <a target="_blank" title="Twitter" class="b-share__handle" href="#"><span class="b-share-icon b-share-icon_twitter"></span></a>
                     <a target="_blank" title="Одноклассники" class="b-share__handle" href="#"><span class="b-share-icon b-share-icon_odnoklassniki"></span></a>
                     <a target="_blank" title="МойМир" class="b-share__handle" href="#"><span class="b-share-icon b-share-icon_moimir"></span></a>
                     --%><a target="_blank" title="Google+" class="b-share__handle" href="https://plus.google.com/b/105589562294750233643/105589562294750233643"><span class="b-share-icon b-share-icon_gplus"></span></a>
                </li>
            </ul>
        </div>
        <div class="clear"></div>
    </div>
    <div class="copyright grey-line">
        &copy; YouTasked, 2013
    </div>
</div>
</body>
</html>

src/main/webapp/WEB-INF/jsp/home.jsp
Hello page!!!

src/main/webapp/WEB-INF/jsp/index.jsp
Hello page!!!

src/main/webapp/WEB-INF/jsp/login.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@taglib uri="http://www.springframework.org/tags" prefix="spring" %>
<%@ page session="true" %>
<html>
<head>
    <title><spring:message code="page.title.login"/></title>
    <meta name="keywords" content="<spring:message code='page.keywords'/>">
    <meta name="description" content="<spring:message code='page.description'/>">
</head>
<body>
<div class="container login-container">
    <div class="login-block">
        <div>
            <h2><spring:message code="enter"/></h2>
            <a id="password-request" href="#" class="grey forgot-link"><spring:message code="forgot.password"/></a>
            <div class="password-request-div">

            </div>
            <div class="clear"></div>
        </div>
        <form action="/j_spring_security_check" class="form-horizontal" method='POST'>
            <div>
                <input type="email" class="inputEmail" name='j_username' autofocus="autofocus" value="${param.email}" placeholder="<spring:message code='your.email' />">
            </div>
            <div>
                <input type="password" class="inputPass" placeholder="<spring:message code='your.pass' />" name='j_password'>
            </div>
            <c:if test="${param.error}">
                <div class="text-error left-align"><spring:message code="AbstractUserDetailsAuthenticationProvider.badCredentials" arguments="${SPRING_SECURITY_LAST_EXCEPTION.message}"/></div>
            </c:if>
            <div class="buttons">
                <div class="checkbox">
                    <input type="checkbox" id="checkbox1" name='_spring_security_remember_me'> <label
                        for="checkbox1"><spring:message code="remember.me"/></label>
                </div>
                <button type="submit" class="btn-enter pull-right"><spring:message code="enter"/></button>
               <div class="clear"></div>
            </div>
        </form>
        <div class="clear"></div>
        <div class="social-block">
            <c:forEach var="network" items="${networks}">
                <a href="${network.loginUrl}" class="${network.type}"></a>
            </c:forEach>
        </div>
    </div>
</div>
<script>
    $(function() {
        Login.init();
    });
</script>
</body>
</html>

src/main/webapp/WEB-INF/jsp/password-recovery.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@taglib uri="http://www.springframework.org/tags" prefix="spring"%>
<html>
    <head>
        <title><spring:message code="password.recovery" /></title>
    </head>
    <body>
        <div class="container main-container">
            <div class="register-block">
                <form method='POST'>
                    <h2><spring:message code="password.recovery" /></h2>
                    <div>
                        <label for="password" class="grey">
                            <spring:message code="password"  />
                        </label>
                        <div>
                            <input type="password" class="inputPass" id="password"  placeholder="<spring:message code="password" />" name='password' autofocus="autofocus" autocomplete="off">
                        </div>
                        <div class="clear"></div>
                    </div>
                    <div>
                        <label for="password2" class="grey">
                            <spring:message code="password2"  />
                        </label>
                        <div>
                            <input type="password" class="inputPass" id="password2"  placeholder="<spring:message code="password2" />" name='password2' autocomplete="off">
                        </div>
                        <div class="clear"></div>
                    </div>

                    <div>
                        <button type="submit" class="register-btn change-pass-btn">
                            <spring:message code="change.password.btn" />
                        </button>
                        <div class="clear"></div>
                    </div>
                </form>
            </div>
        </div>
    </body>
</html>

src/main/webapp/WEB-INF/jsp/password-request.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@taglib uri="http://www.springframework.org/tags" prefix="spring"%>

<div id="passwordRequest" class="passwordRequest" title="<spring:message code='password.recovery' />">
    <form method='POST' action="/password-request" id="passwordRequestForm">
        <div class="text-error"></div>
        <div>
            <input type="email" id="email" class="inputEmail" placeholder="<spring:message code="email" />" name='userEmail' autofocus="autofocus">
            <button type="submit" class="recovery-btn">
                <spring:message code="password.recovery.btn" />
            </button>
        </div>
    </form>
</div>
<script>
    $(function() {
        Request.init();
    });
</script>